# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mmg's blog
email: collstudent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Unemployed for now...
#baseurl: "/jekyll-simple" # the subpath of your site, e.g. /blog
#url: "http://wildflame.me" # the base hostname & protocol for your site
twitter_username: mmg10 
github_username:  mmg10 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
# disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
